"""empty message

Revision ID: 0c5f7c181286
Revises: 3474ca48d58d
Create Date: 2020-03-25 16:38:53.138259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '0c5f7c181286'
down_revision = '3474ca48d58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('date_receive', sa.DATETIME(), nullable=False))
    op.drop_column('notification', 'date_received')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('date_received', mssql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('notification', 'date_receive')
    # ### end Alembic commands ###
