"""empty message

Revision ID: 3474ca48d58d
Revises: d96897410187
Create Date: 2020-03-25 16:21:07.837517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3474ca48d58d'
down_revision = 'd96897410187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('date_received', sa.TIMESTAMP(), nullable=False))
    op.add_column('notification', sa.Column('delete_bool', sa.Integer(), nullable=True))
    op.drop_column('notification', 'delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('delete', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('notification', 'delete_bool')
    op.drop_column('notification', 'date_received')
    # ### end Alembic commands ###
