"""empty message

Revision ID: 612088619d85
Revises: 7a531f682b30
Create Date: 2020-04-06 21:22:35.117954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612088619d85'
down_revision = '7a531f682b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_img', sa.String(length=255), nullable=True))
    op.drop_column('room', 'room_imga')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_imga', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('room', 'room_img')
    # ### end Alembic commands ###
