"""empty message

Revision ID: 99aea7f8c9e2
Revises: 87d88f3c13bc
Create Date: 2020-04-13 14:31:18.029911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99aea7f8c9e2'
down_revision = '87d88f3c13bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('machine_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machines', 'machine_image', ['machine_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_column('machines', 'machine_image_id')
    # ### end Alembic commands ###
