"""empty message

Revision ID: a026ce9ae8bb
Revises: e3f8bffe601b
Create Date: 2020-03-25 16:57:39.092363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a026ce9ae8bb'
down_revision = 'e3f8bffe601b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool__user', 'check_in_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool__user', 'check_in_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
