"""empty message

Revision ID: a3ebb9def4fa
Revises: fd79ff48b694
Create Date: 2020-03-25 16:54:12.360069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'a3ebb9def4fa'
down_revision = 'fd79ff48b694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('time', mssql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
