"""empty message

Revision ID: c07fc8f014a7
Revises: 99aea7f8c9e2
Create Date: 2020-04-18 20:51:46.243812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07fc8f014a7'
down_revision = '99aea7f8c9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_join', sa.Column('machine_id', sa.Integer(), nullable=True))
    op.add_column('machine_join', sa.Column('room', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machine_join', 'machines', ['machine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machine_join', type_='foreignkey')
    op.drop_column('machine_join', 'room')
    op.drop_column('machine_join', 'machine_id')
    # ### end Alembic commands ###
