"""empty message

Revision ID: d3f06581798a
Revises: 835746a9715a
Create Date: 2019-12-08 13:25:33.054507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f06581798a'
down_revision = '835746a9715a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('booking_For_Date', sa.DATE(), nullable=True),
    sa.Column('Start_Time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_join.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'group_join', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'request', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'request', 'machines', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'request', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'staff', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'student', 'machines', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'student', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'student', 'majors', ['major_id'], ['id'])
    op.create_foreign_key(None, 'student', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(None, 'student_level', 'machines', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'student_level', 'student', ['student_id'], ['id'])
    op.create_foreign_key(None, 'student_level', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_level', type_='foreignkey')
    op.drop_constraint(None, 'student_level', type_='foreignkey')
    op.drop_constraint(None, 'student_level', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'group_join', type_='foreignkey')
    op.drop_table('booking')
    # ### end Alembic commands ###
