"""empty message

Revision ID: e3f8bffe601b
Revises: e400ef5ff950
Create Date: 2020-03-25 16:56:18.770424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f8bffe601b'
down_revision = 'e400ef5ff950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool__user', sa.Column('check_in_date', sa.Date(), nullable=False))
    op.add_column('tool__user', sa.Column('check_out_date', sa.Date(), nullable=True))
    op.drop_column('tool__user', 'check_in_dates')
    op.drop_column('tool__user', 'check_out_dates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool__user', sa.Column('check_out_dates', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tool__user', sa.Column('check_in_dates', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('tool__user', 'check_out_date')
    op.drop_column('tool__user', 'check_in_date')
    # ### end Alembic commands ###
