"""empty message

Revision ID: e400ef5ff950
Revises: a3ebb9def4fa
Create Date: 2020-03-25 16:55:37.138471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e400ef5ff950'
down_revision = 'a3ebb9def4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool__user', sa.Column('check_in_dates', sa.Date(), nullable=False))
    op.add_column('tool__user', sa.Column('check_out_dates', sa.Date(), nullable=True))
    op.drop_column('tool__user', 'check_in_date')
    op.drop_column('tool__user', 'check_out_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool__user', sa.Column('check_out_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tool__user', sa.Column('check_in_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('tool__user', 'check_out_dates')
    op.drop_column('tool__user', 'check_in_dates')
    # ### end Alembic commands ###
