"""empty message

Revision ID: ec89d638f240
Revises: 427cd3caa640
Create Date: 2020-04-06 21:19:06.495824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec89d638f240'
down_revision = '427cd3caa640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_img', sa.String(length=255), nullable=True))
    op.drop_column('room', 'room_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_image', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('room', 'room_img')
    # ### end Alembic commands ###
