"""empty message

Revision ID: f49e0ada4544
Revises: c07fc8f014a7
Create Date: 2020-04-22 18:10:15.485103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49e0ada4544'
down_revision = 'c07fc8f014a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'room_id')
    # ### end Alembic commands ###
