"""empty message

Revision ID: fd79ff48b694
Revises: fec139b3bfe9
Create Date: 2020-03-25 16:52:25.109979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd79ff48b694'
down_revision = 'fec139b3bfe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'time')
    # ### end Alembic commands ###
